name: Build firmware

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout user config
        uses: actions/checkout@v3

      - name: Checkout ZMK
        uses: actions/checkout@v3
        with:
          repository: urob/zmk
          ref: main
          path: zmk

      - name: Set up dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install west and dependencies
        run: |
          pip install west
          west init -l config
          west update
          west zephyr-export
          pip install -r zmk/zephyr/scripts/requirements.txt

      - name: Build for Seeeduino XIAO BLE
        run: |
          west build -s zmk/app -b seeeduino_xiao_ble -d build/roba -- -DSHIELD=roba

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/roba/zephyr/zmk.uf2
